#!/usr/bin/env bash

alias miso='sudo mount -o loop -t iso9660'
alias x_full="xrandr --output LVDS --mode 1280x800 --pos 0x424 --output VGA-0 --mode 1280x1024 --pos 1280x0"
alias x_copy="xrandr --output LVDS --mode 1280x800 --output VGA-0 --mode 1280x1024"
alias rbarbuk='rdesktop -g 1024x768 -P -z -x m -r sound:off -u "barbuk" 172.16.0.1:3389 -k fr'
alias bmux='tmux -2 attach-session -t buk'
alias xev="xev | grep -A2 --line-buffered '^KeyRelease' | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'"
alias pip-update="pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo -H pip install -U"

# enable color support of ls and also add handy aliases
alias dir='dir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias bzgrep='bzgrep --color=auto'
alias zgrep='zgrep --color=auto'

# some more ls aliases
alias ll='eza --classify -l --icons --git --color=always'
alias l='ls -lh'

alias q='exit'
alias ss='netstat -tanpu'
alias _="sudo -s"
alias __="sudo -i"
alias c='clear'
alias o='xdg-open'

alias tmux='tmux -2'
alias s='ssh_connect'
alias n='open_monitoring'
alias dsh-update='(cd ~/.dsh && git pull && make clean && make all && make all)'
alias backup='sudo --preserve-env borg create --filter=AME --stats --progress --compression zstd --exclude-caches --exclude-from ~/.dotfiles/apps/backup-excludes ::"{hostname}-{now:%Y-%m-%dT%H-%M-%S}" /'
alias backup-prune='sudo --preserve-env borg prune -v --stats --list --glob-archives "{hostname}-*" --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --keep-yearly 1 && sudo --preserve-env borg compact'
alias backup-list='sudo --preserve-env borg list'
alias pss='ps --ppid 2 -p 2 --deselect awfo user,pid,ppid,pcpu,pmem,vsz,rss,tty,stat,start,time,cgroup,command:220'
alias wifi-taff='sudo create_ap --daemon wlan lan fcZ7XWSasn7r bukbukbuk'
alias local-timezone='curl -s https://ipapi.co/timezone'
alias set-local-timezone='timedatectl set-timezone $(curl -s https://ipapi.co/timezone)'
alias set-france-timezone='timedatectl set-timezone Europe/Paris'
alias set-maurice-timezone='timedatectl set-timezone Indian/Mauritius'
alias gd='GIT_PAGER="delta --light --syntax-theme=gruvbox-light" git diff'
alias lg='lazygit'
alias gg='git log --graph --pretty=format:"%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(reset) %C(cyan)%cd %C(blue)(%cr)%Creset" --date=format:"%Y-%m-%d %Hh%M"'
alias ggf='git log --graph --date=short --pretty=format:'\''%C(auto)%h %Cgreen%an%Creset %Cblue%cd%Creset %C(auto)%d %s'\'''
alias ggs='gg --stat'
alias ggup='git log --branches --not --remotes --no-walk --decorate --oneline' # FROM https://stackoverflow.com/questions/39220870/in-git-list-names-of-branches-with-unpushed-commits
alias gll='git log --graph --pretty=oneline --abbrev-commit'
alias gnew='git log HEAD@{1}..HEAD@{0}' # Show commits since last pull, see http://blogs.atlassian.com/2014/10/advanced-git-aliases/
alias gwc='git whatchanged'
alias gs='git status'
alias gss='git status -s'
alias ans=ansible
alias ap=ansible-playbook

GRC="$(which grc)"
if [ -n "$GRC" ]; then
    alias colourify="$GRC -es"
    alias blkid='colourify blkid'
    alias configure='colourify ./configure'
    alias df='colourify df'
    alias diff='colourify diff'
    alias docker='colourify docker'
    alias docker-compose='colourify docker-compose'
    alias docker-machine='colourify docker-machine'
    alias du='colourify du'
    alias free='colourify free'
    alias fdisk='colourify fdisk'
    alias findmnt='colourify findmnt'
    alias make='colourify make'
    alias gcc='colourify gcc'
    alias g++='colourify g++'
    alias id='colourify id'
    alias ip='colourify ip'
    alias iptables='colourify iptables'
    alias as='colourify as'
    alias gas='colourify gas'
    alias kubectl='colourify kubectl'
    alias ld='colourify ld'
    alias lsof='colourify lsof'
    alias lsblk='colourify lsblk'
    alias lspci='colourify lspci'
    alias netstat='colourify netstat'
    alias ping='colourify ping -O'
    alias ss='colourify ss'
    alias traceroute='colourify traceroute'
    alias traceroute6='colourify traceroute6'
    alias head='colourify head'
    alias tail='colourify tail'
    alias dig='colourify dig'
    alias mount='colourify mount'
    alias ps='colourify ps'
    alias mtr='colourify mtr'
    alias semanage='colourify semanage'
    alias getsebool='colourify getsebool'
    alias ifconfig='colourify ifconfig'
    alias sockstat='colourify sockstat'
fi
