#!/usr/bin/env bash
# shellcheck disable=1090
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

stty stop undef

dot_dir="$HOME/.dotfiles"

eval "$(lua "$dot_dir/modules/z.lua/z.lua" --init bash enhanced once fzf)"

. "$HOME/.tokens"
. "$dot_dir/shell/export"
. "$BASH_IT/bash_it.sh"
. "$dot_dir/shell/aliases"
. "$dot_dir/shell/functions"
. "$dot_dir/shell/systemd_helpers"
. "$dot_dir/shell/completion"

if [ "$(uname)" = "Darwin" ]; then
  . "$dot_dir/shell/darwin"
else
  . "$dot_dir/shell/linux"
  . "$dot_dir/shell/keychain"
fi

export TERM=xterm-256color
