#!/usr/bin/env bash
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '
stty stop undef
shopt -s checkwinsize

dot_dir="$HOME/.dotfiles"
modules_dir="$HOME/.modules"
export PATH="$PATH:$dot_dir/bin"

. "$HOME/.tokens"
. "$dot_dir/shell/export"
. "$BASH_IT/bash_it.sh"
. "$dot_dir/shell/aliases"
. "$dot_dir/shell/functions"
. "$dot_dir/shell/systemd_helpers"
. "$dot_dir/shell/completion"
. "$modules_dir/goto"
_Z_OWNER="$USER"
. "$modules_dir/z"
. "$modules_dir/fz"

if [ "$(uname)" = "Darwin" ]; then
    . "$dot_dir/shell/darwin"
else
    . "$dot_dir/shell/linux"
    . "$dot_dir/shell/keychain"
fi

PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND }'printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'
export TERM=xterm-256color
