#!/usr/bin/env bash
give_me_hostname="$HOME/.dotfiles/bin/give_me_hostname"
# To redraw line after fzf closes (printf '\e[5n')
bind '"\e[0n": redraw-current-line'
export FZF_DEFAULT_COMMAND='ag -g ""'
export COMP_WORDBREAKS=${COMP_WORDBREAKS/\:/}

_complete() {
    local CURRENT_PROMPT="${COMP_WORDS[COMP_CWORD]}"

    if [[ ${CURRENT_PROMPT} == *@*  ]] ; then
        local OPTIONS="-P ${CURRENT_PROMPT/@*/}@ -- ${CURRENT_PROMPT/*@/}"
    else
        local OPTIONS=" -- ${CURRENT_PROMPT}"
    fi

    local ssh_hosts
    ssh_hosts=$1
    COMPREPLY=( $(compgen -W "$ssh_hosts"  ${OPTIONS}) )

    return 0
}

_complete_ssh() {
  _complete < <(give_me_hostname ssh)
}

_complete_net() {
  _complete < <(give_me_hostname)
}

_fzf_complete_ssh() {
  _fzf_complete '+m' "$@" < <(give_me_hostname ssh)
}

_fzf_complete_net() {
  _fzf_complete '+m' "$@" < <(give_me_hostname)
}

_fzf_compgen_path() {
  ag -g "" "$1"
}

_fzf_complete() {
  local selected fzf post
  local CURRENT_PROMPT="${COMP_WORDS[COMP_CWORD]}"
  local OPTIONS=''
  post="$(caller 0 | awk '{print $2}')_post"
  type -t "$post" > /dev/null 2>&1 || post=cat
  fzf="fzf --height 25%"

  if [[ ${CURRENT_PROMPT} == *@*  ]] ; then
      OPTIONS="${CURRENT_PROMPT/@*/}@"
      CURRENT_PROMPT="${CURRENT_PROMPT/*@/}"
  fi

  selected=$(cat | $fzf --select-1 --height 30% --reverse --inline-info +s $1 -q "$CURRENT_PROMPT" | $post | tr '\n' ' ')
  selected=${selected% } # Strip trailing space not to repeat "-o nospace"
  printf '\e[5n'

  if [ -n "$selected" ]; then
    COMPREPLY=(${OPTIONS}"$selected")
    return 0
  fi

}

__fzf_history__() {
  local line
  shopt -u nocaseglob nocasematch
  line=$(
    HISTTIMEFORMAT= history |
    FZF_DEFAULT_OPTS="--height 25% $FZF_DEFAULT_OPTS +s --tac -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS +m" fzf |
    command grep '^ *[0-9]') &&
    if [[ $- =~ H ]]; then
      sed 's/^ *\([0-9]*\)\** .*/!\1/' <<< "$line"
    else
      sed 's/^ *\([0-9]*\)\** *//' <<< "$line"
    fi
}

_fzf_complete_kill() {
  [ -n "${COMP_WORDS[COMP_CWORD]}" ] && return 1

  local selected fzf
  fzf="fzf"
  selected=$(ps -ef | sed 1d | FZF_DEFAULT_OPTS="--height 25% \
      --min-height 15 --reverse $FZF_DEFAULT_OPTS --preview 'echo {}' --preview-window down:3:wrap \
      $FZF_COMPLETION_OPTS" $fzf -m | awk '{print $2}' | tr '\n' ' ')
  printf '\e[5n'

  if [ -n "$selected" ]; then
    COMPREPLY=( "$selected" )
    return 0
  fi
}

__fzf_select__() {
  local cmd="${FZF_CTRL_T_COMMAND:-"command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
    -o -type f -print \
    -o -type d -print \
    -o -type l -print 2> /dev/null | cut -b3-"}"
  eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_CTRL_T_OPTS" fzf -m "$@" | while read -r item; do
    printf '%q ' "$item"
  done
  echo
}

fzf-file-widget() {
  local selected="$(__fzf_select__)"
  READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
  READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
}

__fzf_cd__() {
  local cmd dir
  cmd="${FZF_ALT_C_COMMAND:-"command find -L . \\( -path '*/\\.*' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
    -o -type d -print 2> /dev/null | sed 1d | cut -b3-"}"
  dir=$(eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_ALT_C_OPTS" fzf +m) && printf 'cd %q' "$dir"
}

# v - open files in ~/.viminfo
v() {
  local files
  files=$(grep '^>' ~/.viminfo | cut -c3- |
          while read -r line; do
            [ -f "${line/\~/$HOME}" ] && echo "${line/\~/$HOME}"
          done | fzf-tmux --select-1 --reverse --inline-info +s \
            --tac -m --preview 'highlight --force -O ansi -l {} 2> /dev/null | head -200' --query "$*" -1) \
            && vim "${files//\~/$HOME}"
}

fmpc() {
  local song_position
  song_position=$(mpc -f "%position%) %artist% - %title%" playlist | \
    fzf-tmux --query="$1" --height 30% --reverse --inline-info +s --select-1 --exit-0 | \
    sed -ne 's/^\([0-9].*\)).*/\1/p') || return 1
  [ -n "$song_position" ] && mpc -q play "$song_position"
}

# Net tools completions
net_tools="ping host mtr mosh telnet ftp dig drill nslookup"
ssh_tools="ssh s n rsync scp sftp"
if hash fzf 2>/dev/null; then
    complete -o default -o bashdefault -o nospace -F _fzf_complete_net $net_tools
    complete -o default -o bashdefault -o nospace -F _fzf_complete_ssh $ssh_tools
else
    complete -o default -o bashdefault -o nospace -F _complete_net $net_tools
    complete -o default -o bashdefault -o nospace -F _complete_ssh $ssh_tools
fi

# Kill completion
complete -F _fzf_complete_kill -o nospace -o default -o bashdefault kill

# Required to refresh the prompt after fzf
bind '"\er": redraw-current-line'
bind '"\e^": history-expand-line'
# CTRL-R - Paste the selected command from history into the command line
bind '"\C-r": " \C-e\C-u`__fzf_history__`\e\C-e\e^\er"'
# CTRL-T - Paste the selected file path into the command line
bind -x '"\C-f": "fzf-file-widget"'
# ALT-C - cd into the selected directory
bind '"\ed": " \C-e\C-u`__fzf_cd__`\e\C-e\er\C-m"'
