#!/usr/bin/env bash
export LC_ALL=en_US.UTF-8
export GIT_HOSTING='git@github.com'
# Update window size after every command
shopt -s checkwinsize
# Append to the history file, don't overwrite it
shopt -s histappend
# Save multi-line commands as one command
shopt -s cmdhist
# Prepend cd to directory names automatically
shopt -s autocd 2>/dev/null
# Correct spelling errors during tab-completion
shopt -s dirspell 2>/dev/null
# Correct spelling errors in arguments supplied to cd
shopt -s cdspell 2>/dev/null
CDPATH="."
# Automatically trim long paths in the prompt (requires Bash 4.x)
PROMPT_DIRTRIM=3
# Enable history expansion with space
# E.g. typing !!<space> will replace the !! with your last command
bind Space:magic-space
# Turn on recursive globbing (enables ** to recurse all directories)
shopt -s globstar 2>/dev/null
# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob
# Perform file completion in a case insensitive fashion
bind "set completion-ignore-case on"
# Treat hyphens and underscores as equivalent
bind "set completion-map-case on"
# Display matches for ambiguous patterns at first tab press
bind "set show-all-if-ambiguous on"
# Immediately add a trailing slash when autocompleting symlinks to directories
bind "set mark-symlinked-directories on"
# Enable incremental history search with up/down arrows (also Readline goodness)
# Learn more about this here: http://codeinthehole.com/writing/the-most-important-command-line-tip-incremental-history-searching-with-inputrc/
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\e[C": forward-char'
bind '"\e[D": backward-char'

export LESS='--chop-long-lines --ignore-case --quit-if-one-screen --RAW-CONTROL-CHARS --no-init'
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# Huge history. Doesn't appear to slow things down, so why not?
HISTFILE="$HOME/.bash_history_$USER"
HISTSIZE=100000
HISTFILESIZE=$HISTSIZE

# Don't record some commands
HISTIGNORE="&:[ ]*:exit:history:clear:?:??"
HISTTIMEFORMAT='%F %T '

# Avoid duplicate entries
HISTCONTROL="erasedups:ignoreboth:autosave"

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export GREP_COLORS='mt=1;33'
export MANPAGER="less --no-init --RAW-CONTROL-CHARS"

# Path to the bash it configuration
export BASH_IT=$HOME/.bash_it
export SCM_GIT_SHOW_DETAILS=true
export THEME_SHOW_RUBY_PROMPT=false
export SCM_CHECK=true
export BASH_IT_COMMAND_DURATION=true

# Bashit theme
export BASH_IT_THEME='barbuk'

# Bat theme
export BAT_THEME="GitHub"

# Set my editor and git editor
export EDITOR="vim"
export GIT_EDITOR='vim'

# Langage options
export RUBYOPT='-W:no-deprecated'

# Don't check mail when opening terminal.
unset MAILCHECK
export IRC_CLIENT='irssi'

# https://github.com/sickill/stderred
stderred=/usr/lib/libstderrred.so
if [ -e "$stderred" ]; then
    export LD_PRELOAD="/usr/lib/libstderred.so${LD_PRELOAD:+:$LD_PRELOAD}"
fi

# gpg tty
GPG_TTY=$(tty)
export GPG_TTY
