#!/usr/bin/env bash
export LC_ALL=en_US.UTF-8
export GIT_HOSTING='git@github.com'
# Prevent file overwrite on stdout redirection
set -o noclobber
# Update window size after every command
shopt -s checkwinsize
# Append to the history file, don't overwrite it
shopt -s histappend
# Save multi-line commands as one command
shopt -s cmdhist
# Prepend cd to directory names automatically
shopt -s autocd
# Correct spelling errors during tab-completion
shopt -s dirspell
# Correct spelling errors in arguments supplied to cd
shopt -s cdspell
CDPATH="."

export LESS='-S'
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# Huge history. Doesn't appear to slow things down, so why not?
HISTSIZE=10000
HISTFILESIZE=$HISTSIZE
# Don't record some commands
HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear:c:q:gg:s:gs:ll:l:env:?:??"
HISTTIMEFORMAT="%b %d %R:%S %Y: "
# Avoid duplicate entries
HISTCONTROL="erasedups:ignoreboth"
# Record each line as it gets issued
_bash_history_sync() {
  builtin history -a
  HISTFILESIZE=$HISTSIZE
  builtin history -c
  builtin history -r
}
history() {
  _bash_history_sync
  builtin history "$@"
}
PROMPT_COMMAND=_bash_history_sync
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export GREP_COLOR="1;33"

# Path to the bash it configuration
export BASH_IT=$HOME/.bash_it
export SCM_GIT_SHOW_DETAILS=true
export SCM_CHECK=true

export BASH_IT_THEME='barbuk'

# Set my editor and git editor
export EDITOR="vim"
export GIT_EDITOR='vim'

# Don't check mail when opening terminal.
unset MAILCHECK
export IRC_CLIENT='irssi'
