#!/usr/bin/env bash
ipreverse() {
    if [ "$(uname)" = "Darwin" ]; then
        tac=gtac
    else
        tac=tac
    fi
    echo -n "$1" | grep -o -E '([0-9]{1,3}\.){3}' | $tac -s.
}

#=() { qalc $*; }

t () {
    if [[ "$*" == "" ]]; then
        cat ~/.t;
    else
        echo "  ☐ $*" >> ~/.t;
    fi
}
