#!/usr/bin/env bash

export COMP_WORDBREAKS=${COMP_WORDBREAKS/\:/}

_sshcomplete() {
    local CURRENT_PROMPT="${COMP_WORDS[COMP_CWORD]}"

    if [[ ${CURRENT_PROMPT} == *@*  ]] ; then
        local OPTIONS="-P ${CURRENT_PROMPT/@*/}@ -- ${CURRENT_PROMPT/*@/}"
    else
        local OPTIONS=" -- ${CURRENT_PROMPT}"
    fi

    local ssh_hosts
    ssh_hosts=$("$HOME/.dotfiles/bin/give_me_hostname")
    COMPREPLY=( $(compgen -W "$ssh_hosts"  ${OPTIONS}) )

    return 0
}

_fzf_complete_ssh() {
  _fzf_complete '+m' "$@" < <("$HOME/.dotfiles/bin/give_me_hostname")
}

_fzf_complete() {
  local selected fzf post
  local CURRENT_PROMPT="${COMP_WORDS[COMP_CWORD]}"
  local OPTIONS=''
  post="$(caller 0 | awk '{print $2}')_post"
  type -t "$post" > /dev/null 2>&1 || post=cat
  fzf="fzf"

  if [[ ${CURRENT_PROMPT} == *@*  ]] ; then
      OPTIONS="${CURRENT_PROMPT/@*/}@"
      CURRENT_PROMPT="${CURRENT_PROMPT/*@/}"
  fi

  tput sc
  selected=$(cat | $fzf --select-1 $FZF_COMPLETION_OPTS $1 -q "$CURRENT_PROMPT" | $post | tr '\n' ' ')
  selected=${selected% } # Strip trailing space not to repeat "-o nospace"
  tput rc

  if [ -n "$selected" ]; then
    COMPREPLY=(${OPTIONS}"$selected")
    return 0
  fi

}

net_tools="scp sftp ssh autossh s n ping rsync host mtr mosh telnet ftp dig drill nslookup"
if hash fzf 2>/dev/null; then
    complete -o default -o bashdefault -o nospace -F _fzf_complete_ssh $net_tools
else
    complete -o default -o bashdefault -o nospace -F _sshcomplete $net_tools
fi
