#!/usr/bin/env bash
ssh_agent_file="$XDG_RUNTIME_DIR/.ssh-agent-thing"

if [ ! -f "$ssh_agent_file" ]; then
  touch "$ssh_agent_file"
  mapfile -t live_keys < <(find "$HOME"/.ssh/keys/live -not -type d -not -name '*.pub')
  chmod 600 "$ssh_agent_file"
  keychain add \
    --systemd \
    --eval \
    --quiet \
    --dir="$XDG_RUNTIME_DIR" \
    --absolute \
    --quick \
    --no-inherit \
    --timeout 720 \
    "${live_keys[@]}" \
    >"$ssh_agent_file"
  eval "$(<"$ssh_agent_file")"
elif grep -q '^SSH_AUTH_SOCK=/run/user/' "$ssh_agent_file"; then
  eval "$(<"$ssh_agent_file")"
fi
