#!/usr/bin/env bash
eval "$(dircolors -b $HOME/.dir_colors)"
eval "$(rbenv init -)"
alias ls='ls --color=auto'
alias up='yay -Syu --noconfirm'
alias yaourt='yay'
alias usb3='sudo modprobe -r xhci_pci && sudo modprobe xhci-pci'
alias ping='ping -O'

bupc() {
    up
    pip freeze --local \
    | grep -v '^\-e' \
    | cut -d = -f 1  \
    | xargs -n1 sudo -H pip install -U
    gem update --system
    gem update
    rbenv rehash
}

xclip=$(command -v xclip)

pbcopy() {
    $xclip -selection clipboard
}
pbpaste() {
    $xclip -selection clipboard -o
}

