#!/usr/bin/env bash
eval "$(dircolors -b "$HOME"/.dir_colors)"
# rbenv gem
if [ -d "$HOME/.rbenv/shims" ]; then
    export PATH="$HOME/.rbenv/shims:${PATH}"
    export RBENV_SHELL=bash
else
    # system ruby gem
    ruby_gem_bin_dir=$(gem env | awk '/USER INSTALLATION DIRECTORY/ {print $NR}')
    if [ -d "$ruby_gem_bin_dir/bin" ]; then
        export PATH="$ruby_gem_bin_dir/bin:${PATH}"
    fi
fi

alias ls='ls --color=auto'
alias up='yay -Syu --noconfirm'
alias yaourt='yay'
alias usb3='sudo modprobe -r xhci_pci && sudo modprobe xhci-pci'
alias ping='ping -O'

bupc() {
    update_gem
    update_vagrant
    rustup update
    up
}

update_gem() {
    gem update --system
    gem update
    gem cleanup
    rbenv rehash
}

update_vagrant() {
    vagrant plugin update
    vagrant box update
    vagrant box prune
}

pbcopy() {
    xclip -selection clipboard
}

pbpaste() {
    xclip -selection clipboard -o
}
