#!/usr/bin/env bash
if command -v vivid >/dev/null 2>&1; then
    LS_COLORS="$(vivid generate ayu_bold)"
    export LS_COLORS
else
    eval "$(dircolors -b "$HOME"/.dir_colors)"
fi
if command -v batman >/dev/null 2>&1; then
    eval "$(batman --export-env)"
fi
# rbenv gem
if [ -d "$HOME/.rbenv/shims" ]; then
    export PATH="$HOME/.rbenv/shims:${PATH}"
    export RBENV_SHELL=bash
else
    # system ruby gem
    if [ -e /tmp/ruby_gem_bin_dir ]; then
        ruby_gem_bin_dir="$(< /tmp/ruby_gem_bin_dir)"
    else
        ruby_gem_bin_dir=$(gem env user_gemhome | tee /tmp/ruby_gem_bin_dir)
    fi
    if [ -d "$ruby_gem_bin_dir/bin" ]; then
        export PATH="$ruby_gem_bin_dir/bin:${PATH}"
    fi
fi

alias ls='ls --color=auto'
alias up='yay -Syu --noconfirm'
alias yaourt='yay'
alias usb3='sudo modprobe -r xhci_pci && sudo modprobe xhci-pci'

bupc() {
    update_gem
    update_vagrant
    update_rustup
    clean_local_packages
    up
}

update_gem() {
    if command -v gem >/dev/null 2>&1; then
        gem update --system
        gem update
        gem cleanup
    fi
    if command -v rbenv >/dev/null 2>&1; then
        rbenv rehash
    fi
}

update_rustup() {
    if command -v rustup >/dev/null 2>&1; then
        rustup update
    fi
}

update_vagrant() {
    if command -v vagrant >/dev/null 2>&1; then
        vagrant plugin update
        vagrant box update
        vagrant box prune
    fi
}

clean_go() {
    if command -v go >/dev/null 2>&1; then
        go clean -cache -modcache
    fi
}

clean_cargo() {
    if command -v cargo >/dev/null 2>&1; then
        cargo install --quiet cargo-cache
        cargo cache -a
    fi
}

clean_npm() {
    if command -v npm >/dev/null 2>&1; then
        npm cache verify >/dev/null 2>&1
    fi
    if command -v yarn >/dev/null 2>&1; then
        yarn cache clean >/dev/null 2>&1
    fi
    if command -v pnpm >/dev/null 2>&1; then
        pnpm store prune >/dev/null 2>&1
    fi
}

clean_nuget() {
    if command -v dotnet >/dev/null 2>&1; then
        dotnet nuget locals --clear all
    fi
}

clean_local_packages() {
    clean_go
    clean_cargo
    clean_npm
    clean_nuget
}

pbcopy() {
    xclip -selection clipboard
}

pbpaste() {
    xclip -selection clipboard -o
}
