#!/usr/bin/env bash

start() {
    systemctl start "$@"
    systemctl status "$@"
}

restart() {
    systemctl restart "$@"
    systemctl status "$@"
}

stop() {
    systemctl stop "$@"
    systemctl status "$@"
}

enable() {
    systemctl enable "$@"
    systemctl status "$@"
}

status() {
    systemctl status "$@"
}

disable() {
    systemctl disable "$@"
    systemctl status "$@"
}

error_log() {
    journalctl -p 3 -xb
}

service_failed() {
    systemctl --failed
}
