---
extends: default

rules:
  line-length:
    max: 260
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  comments:
    # prettier compatibility
    min-spaces-from-content: 1
  comments-indentation: false
  document-start:
    present: true
  key-duplicates:
    forbid-duplicated-merge-keys: true
  indentation:
    level: error
    indent-sequences: consistent
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
