#!/usr/bin/env bash

alias up='yaourt -Syu --aur --noconfirm'
alias miso='sudo mount -o loop -t iso9660'
alias x_full="xrandr --output LVDS --mode 1280x800 --pos 0x424 --output VGA-0 --mode 1280x1024 --pos 1280x0"
alias x_copy="xrandr --output LVDS --mode 1280x800 --output VGA-0 --mode 1280x1024"
alias rbarbuk='rdesktop -g 1024x768 -P -z -x m -r sound:off -u "barbuk" 172.16.0.1:3389 -k fr'
alias bmux='tmux -2 attach-session -t buk'
alias xev="xev | grep -A2 --line-buffered '^KeyRelease' | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'"
alias pip-update="pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo -H pip install -U"

# enable color support of ls and also add handy aliases
alias dir='dir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias bzgrep='bzgrep --color=auto'
alias zgrep='zgrep --color=auto'

# some more ls aliases
alias ll='ls -lha'
alias l='ls -lh'

alias q='exit'
alias ss='netstat -tanpu'
alias _="sudo -s"
alias c='clear'
alias o='xdg-open'

alias meteo='curl -4 http://wttr.in'
alias s='ssh_connect'
alias n='open_monitoring'
