#!/usr/bin/env bash

alias flushdns='dscacheutil -flushcache;sudo killall -HUP mDNSResponder;say flushed'

alias bupc="brew update && brew upgrade --all \
    && brew cleanup && softwareupdate -l \
    && pip freeze --local \
    | grep -v '^\-e' \
    | cut -d = -f 1  \
    | xargs -n1 pip install -U"

alias up="z tool && ./cybsecurity-full-process; say -v thomas updated"

. /usr/local/share/bash-completion/bash_completion
