#!/usr/bin/env bash

flushdns() {
    dscacheutil -flushcache
    sudo killall -HUP mDNSResponder
    say flushed
}

bupc() {
    brew update
    brew upgrade
    brew cleanup
    softwareupdate -l
    pip freeze --local \
    | grep -v '^\-e' \
    | cut -d = -f 1  \
    | xargs -n1 pip install -U
}

up() {
    z tool
    ./cybsecurity-full-process
    say -v thomas updated
}

. /usr/local/share/bash-completion/bash_completion
