#!/usr/bin/env bash

export LC_ALL=en_US.UTF-8

export GIT_HOSTING='git@github.com'

# Prevent file overwrite on stdout redirection
set -o noclobber
# Update window size after every command
shopt -s checkwinsize
# Automatically trim long paths in the prompt (requires Bash 4.x)
PROMPT_DIRTRIM=2
# Append to the history file, don't overwrite it
shopt -s histappend
# Save multi-line commands as one command
shopt -s cmdhist
# Record each line as it gets issued
PROMPT_COMMAND='history -a'
# Huge history. Doesn't appear to slow things down, so why not?
HISTSIZE=500000
HISTFILESIZE=100000
# Avoid duplicate entries
HISTCONTROL="erasedups:ignoreboth"
# Don't record some commands
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear:c:q:gg"
# Prepend cd to directory names automatically
shopt -s autocd
# Correct spelling errors during tab-completion
shopt -s dirspell
# Correct spelling errors in arguments supplied to cd
shopt -s cdspell
CDPATH="."

export HISTTIMEFORMAT="%b %d %R:%S %Y: "

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

export GREP_COLOR="1;33"

export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# Don't record some commands
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"
export HISTTIMEFORMAT="%b %d %R:%S %Y: "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export LESS='-S'

# Path to the bash it configuration
export BASH_IT=$HOME/.bash_it
export SCM_GIT_SHOW_DETAILS=true
export SCM_CHECK=true

export BASH_IT_THEME='barbuk'

# Set my editor and git editor
export EDITOR="vim"
export GIT_EDITOR='vim'

# Don't check mail when opening terminal.
unset MAILCHECK
export IRC_CLIENT='irssi'

export SCM_CHECK=true
export SCM_GIT_SHOW_DETAILS=true
