#!/usr/bin/env bash

fan() {
  sensors
  echo level "$@" | sudo tee /proc/acpi/ibm/fan
}

xkcdrandom() { wget -qO- http://dynamic.xkcd.com/comic/random | sed -n 's#^<img src="\(http://imgs.[^"]\+\)"\s\+title="\(.\+\?\)"\salt.\+$#display "\1"\necho '"'\2'#p" | bash; }
translate(){ wget -qO- "http://ajax.googleapis.com/ajax/services/language/translate?v=1.0&q=$1&langpair=$2|${3:-en}" | sed 's/.*"translatedText":"\([^"]*\)".*}/\1\n/'; }
cyanide(){ display "$(wget -q http://explosm.net/comics/random/ -O - | grep -Po 'http://www.explosm.net/db/files/Comics/*/[^"]+(png|jpg|jpeg)')"; }

s() {
    local host="$1"
    local port="$2"

    if [ -z "$host" ]; then
        dsh=$(grep -vE '^#' "$HOME/.dsh/group/all")
        hosts=$(awk '{print $1}' "$HOME/.ssh/known_hosts" | grep -v ^\| | cut -d, -f 1 | sed -e 's/\[//g')

        host="$(echo "$dsh" "$hosts" | sort -u | fzf)"
    fi

    if [ "$(getent hosts "$host" | wc -l)" = 0 ]; then
        echo "$0: unable to resolve hostname $host" >&2
        exit 1
    fi

    if [ -z "$port" ]; then
        port='22'
    fi

    rsync -avz --copy-links --no-o --no-g  -e "ssh -p $port" \
        --exclude='.git/' --exclude='.vim/backup/*' \
        --exclude='doc/' --exclude='test/' \
        --exclude='.vim/swp/*' \
        ~/.dotfiles/server/ \
        "$host":

    echo -ne "\033]0;$host\007"

    ssh -p "$port" -t "$host" \
    "
    if test \$SSH_AUTH_SOCK ; then
        ln -sf \$SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
    fi
    export h=$host
    tmux attach -t buk || tmux new -s buk
    "
}
