#!/usr/bin/env bash

export COMP_WORDBREAKS=${COMP_WORDBREAKS/\:/}

_sshcomplete() {
    local CURRENT_PROMPT="${COMP_WORDS[COMP_CWORD]}"

    if [[ ${CURRENT_PROMPT} == *@*  ]] ; then
        local OPTIONS="-P ${CURRENT_PROMPT/@*/}@ -- ${CURRENT_PROMPT/*@/}"
    else
        local OPTIONS=" -- ${CURRENT_PROMPT}"
    fi

    # parse all hosts found in .dsh/group/all
    if [ -r "$HOME/.dsh/group/all" ]; then
        local ssh_hosts
        ssh_hosts=$(grep -vE '^#' "$HOME/.dsh/group/all")
        COMPREPLY=( $(compgen -W "$ssh_hosts"  ${OPTIONS}) )
    fi

    # parse all hosts found in .ssh/known_hosts
    if [ -r "$HOME/.ssh/known_hosts" ]; then
        if grep -v -q -e '^ ssh-rsa' "$HOME/.ssh/known_hosts" ; then
            COMPREPLY=( ${COMPREPLY[@]} $(compgen -W "$( awk '{print $1}' "$HOME/.ssh/known_hosts" | grep -v ^\| | cut -d, -f 1 | sed -e 's/\[//g' | sed -e 's/\]//g' | cut -d: -f1 | grep -v ssh-rsa)" ${OPTIONS}) )
        fi
    fi

    return 0
}

complete -o default -o nospace -F _sshcomplete scp sftp ssh autossh s ping rsync host mtr mosh telnet
