#!/bin/bash
#
# Copyright (C) 2021 BarbUk <barbarisme@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -o errexit -o pipefail -o nounset

for dir in {z.lua,rmate,tpm,z,bash-it,lain}; do
    (
        cd modules/$dir
        echo -n "Updating module $dir: "
        git pull
    )
done
