#!/usr/bin/env bash

TMUX_BIN=$(echo "$TMUX" | awk -F'[/-]' '{print $3}')

get_tmux_option() {
	local option=$1 default_value=$2 option_value
	option_value=$($TMUX_BIN show-option -gqv "$option")
	[[ -z "$option_value" ]] && echo "$default_value" || echo "$option_value"
}

set_tmux_option() {
	local option=$1
	local value=$2
	$TMUX_BIN set-option -gq "$option" "$value"
}
