continue=true
max-concurrent-downloads=26
bt-detach-seed-only=true
max-connection-per-server=7
min-split-size=1M
split=128
#piece-length=1M
#enable-http-pipelining=false
http-accept-gzip=true
max-overall-download-limit=0
max-download-limit=0
max-overall-upload-limit=0
max-upload-limit=0
user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.7680.177 Safari/537.36

ca-certificate=/etc/ssl/certs/ca-certificates.crt
