#!/bin/bash

# turn bell off
xset -b
# Source default config
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi
# Merge xresources
[[ -f ~/.Xresources ]] && xrdb -merge -I"$HOME" ~/.Xresources
# Export and path definition
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export QT_QPA_PLATFORMTHEME='qt5ct'
export GOPATH="$HOME/.go"
export COMPOSERPATH="$HOME/.composer/vendor/bin"
export CCACHEPATH="/usr/lib/ccache/bin"
export DOTBIN="$HOME/.dotfiles/bin"
export PATH="$DOTBIN:$GOPATH/bin:$COMPOSERPATH:$CCACHEPATH:/usr/local/bin:$PATH"
# Correct screen configuration for x220 or x260
model=$(awk '{print $2}' /sys/devices/virtual/dmi/id/product_version)
case "$model" in
  'x220' )
    export LIBGL_DRI3_DISABLE=1
    xcalib -d :0 "$HOME/.dotfiles/system/icc/lenovo_x220_4290rv5.icc"
    ;;
  'x260' )
    xcalib -d :0 "$HOME/.dotfiles/system/icc/ICC_Lenovo_Thinkpad_X260_1920x1080_non_glossy_N125HCE_GN1.icm"
    ;;
esac
# Use menu key as right clic
#xmodmap -e 'keycode 135 = Menu'
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
# Rename wmname and configure java non reparenting
if command -v wmname >/dev/null 2>&1; then
  wmname LG3D
fi
export _JAVA_AWT_WM_NONREPARENTING=1
# Ssh and keychain configuration
export SSH_ASKPASS=/usr/lib/seahorse/ssh-askpass
eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets)"
eval "$(keychain --eval --agents ssh,gpg)"
# Screensaver timeout and cycle
xset s 120 120
# dpms Standby, Suspend and off
xset dpms 150 200 300
# Lock session after screen save or lid close
xss-lock -- slock &
# pcmanfm daemon, for quick file manager access
#pcmanfm -d &
# Unclutter hide mouse cursor
unclutter --ignore-scrolling --exclude-root --fork
if ! systemctl --user is-active picom.service >/dev/null 2>&1; then
    systemctl --user start picom.service
fi
# Start session
if command -v tdm >/dev/null 2>&1; then
  exec tdm --xstart
fi
