xmodmap -e 'keycode 135 = Menu'
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export QT_QPA_PLATFORMTHEME='qt5ct'
export GOPATH="$HOME/.go"
export COMPOSERPATH="$HOME/.composer/vendor/bin"
export COPEPATH=$(cope_path)
export CCACHEPATH="/usr/lib/ccache/bin"
export PATH="$GOPATH/bin:$COMPOSERPATH:$CCACHEPATH:$COPEPATH:/usr/local/bin:$PATH"
xcalib -d :0 $HOME/.dotfiles/system/lenovo_x220_4290rv5.icc
xset s 120 120
compton --config ~/.compton.conf -b
wmname LG3D
export SSH_ASKPASS=ssh-askpass
eval "$(keychain --eval --agents ssh,gpg)"
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets)
export _JAVA_AWT_WM_NONREPARENTING=1
unclutter --ignore-scrolling --exclude-root --fork
light-locker &
pgrep redshift &> /dev/null || redshift -l -20.2696363:57.4759043 &> /dev/null &
