#!/usr/bin/env bash

# Timeout easily forgotten apps
alias tail='timeout 3600 tail'
alias bzless='timeout 3600 bzless'
alias zless='timeout 3600 zless'
alias top='timeout 3600 top'
alias htop='TERM=screen timeout 3600 htop'

# enable color support of ls and also add handy aliases
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias bzgrep='bzgrep --color=auto'
alias zgrep='zgrep --color=auto'

# some more ls aliases
alias ll='ls -lha'
alias l='ls -lh'

alias q='exit'
alias s='netstat -tanpu'
alias _="sudo -s"
alias __="sudo -i"
alias c='clear'
if hash systemctl 2>/dev/null; then
  alias pss='ps --ppid 2 -p 2 --deselect awfo user,pid,ppid,pcpu,pmem,vsz,rss,tty,stat,start,time,cgroup,command:220'
else
  alias pss='ps --ppid 2 -p 2 --deselect awfo user,pid,ppid,pcpu,pmem,vsz,rss,tty,stat,start,time,command:220'
fi

alias tmux='tmux -2'

# Git
alias gg='git log --graph --pretty=format:"%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(reset) %C(cyan)%cd %C(blue)(%cr)%Creset" --date=format:"%Y-%m-%d %Hh%M"'
alias ggf='git log --graph --date=short --pretty=format:'\''%C(auto)%h %Cgreen%an%Creset %Cblue%cd%Creset %C(auto)%d %s'\'''
alias ggup='git log --branches --not --remotes --no-walk --decorate --oneline' # FROM https://stackoverflow.com/questions/39220870/in-git-list-names-of-branches-with-unpushed-commits
alias gll='git log --graph --pretty=oneline --abbrev-commit'
alias gnew='git log HEAD@{1}..HEAD@{0}' # Show commits since last pull, see http://blogs.atlassian.com/2014/10/advanced-git-aliases/
alias gwc='git whatchanged'
alias gs='git status'
alias gss='git status -s'

# Ssh
ssh_default_options=(
  -o PreferredAuthentications=publickey,keyboard-interactive
  -o StrictHostKeyChecking=accept-new
  -o SetEnv=\'TERM=xterm-256color\'
  -o Compression=no
  -o ConnectTimeout=5
  -o ServerAliveInterval=10
  -o ServerAliveCountMax=2
)

alias ssh='ssh "${ssh_default_options[@]}"'
alias custom_server_config='vim "$HOME/.config/server/custom"'
