#!/usr/bin/env bash

# v - open files in ~/.viminfo
v() {
  local files
  files=$(grep '^>' ~/.viminfo | cut -c3- \
    | while read -r line; do
      [ -f "${line/\~/$HOME}" ] && echo "${line/\~/$HOME}"
    done | fzf --select-1 --reverse --inline-info +s \
    --tac --multi --preview 'highlight --force -O ansi -l {} 2> /dev/null | head -200' --query "$*" -1) \
    && vim "${files//\~/$HOME}"
}

log() {
  local cmd log_file
  cmd="command find /var/log/ -type f -name '*log' 2>/dev/null"
  log_file=$(eval "$cmd" | fzf --height 40% --min-height 25 --tac --tiebreak=length,begin,index --reverse --inline-info) && less "$log_file"
}

define_locale() {
  local locale locales=(
    C.utf8
    C.UTF-8
    en_US.utf8
    en_IE.utf8
    en_GB.utf8
    C
  )

  for locale in "${locales[@]}"; do
    if locale -a | grep -q "^$locale"; then
      export LC_ALL="$locale"
      return
    fi
  done
}
