[ids]

0001:0001:09b4e68d
0001:0001:3cf016cc

[main]

capslock = layer(nav)

[nav]

# nav
j = left
i = up
k = down
l = right
u = pageup
o = pagedown
h = home
n = end

# delete
backspace = delete

# Print
p = print

# Media
q =  previoussong
w = playpause
e = nextsong
a = volumedown
s = mute
d = volumeup

# Mouse layer
tab = layer(mouse)

[mouse]

u = leftmouse
o = rightmouse
h = scrollup
n = scrolldown
# j = command(DISPLAY=:0 xdotool mousemove_relative -- -20 0)
# i = command(xdotool mousemove_relative -- -100 0 --  0  20)
# k = command(xdotool mousemove_relative -- -100 0 --  0 -20)
# l = command(xdotool mousemove_relative -- -100 0 --  20  0)
