#!/usr/bin/env bash
set -e -o pipefail -o nounset

LOCAL="${LOCAL:-${XDG_LOCAL_HOME:-$HOME/.config}/dmenu/edit-list}"
[ -f "$LOCAL" ] || exit 1

. "$HOME/.dmenurc"
DMENU_ARGS="-i $DMENU_CONF -l 10"

file="$(dmenu ${DMENU_ARGS} -p 'edit: ' "$@" < "$LOCAL")"
[ "$file" ] && termite --exec "vim $file" &
