#!/usr/bin/env bash

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export GVIMINIT='let $MYGVIMRC="$XDG_CONFIG_HOME/vim/gvimrc" | source $MYGVIMRC'
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && [ -x /usr/bin/tdm ]; then
  source /usr/bin/tdm
fi

if [[ -f ~/.bashrc ]]; then
  . ~/.bashrc
fi
